export const CHANGE_RECOMMEND_TOP_BANNER = 'CHANGE_RECOMMEND_TOP_BANNER';
export const CHANGE_RECOMEND_HOT_RECOMMEND = 'CHANGE_RECOMEND_HOT_RECOMMEND';
export const CHANGE_RECOMMEND_NEW_ALBUM = 'CHANGE_RECOMMEND_NEW_ALBUM';
export const CHANGE_NEW_LIST = 'CHANGE_NEW_LIST';
export const CHANGE_ORIGIN_LIST = 'CHANGE_ORIGIN_LIST';
export const CHANGE_UP_LIST = 'CHANGE_UP_LIST';
export const CHANGE_SETTLE_SINGERS = 'CHANGE_SETTLE_SINGERS';
export const CHANGE_HOT_RADIO = 'CHANGE_HOT_RADIO';
