export const CHANGE_CURRENT_SONG = 'CHANGE_CURRENT_SONG';
export const CHANGE_SIMI_PLAYLIST = 'CHANGE_SIMI_PLAYLIST';
export const CHANGE_SIMI_SONGS = 'CHANGE_SIMI_SONGS';
export const CHANGE_PLAYLIST = 'CHANGE_PLAYLIST';
export const CHANGE_PLAY_SEQUENCE = 'CHANGE_PLAY_SEQUENCE';
export const CHANGE_CURRENT_SONG_INDEX = 'CHANGE_CURRENT_SONG_INDEX';
export const CHANGE_CURRENT_LYRIC = 'CHANGE_CURRENT_LYRIC';
export const CHANGE_CURRENT_LYRIC_INDEX = 'CHANGE_CURRENT_LYRIC_INDEX';
